---
roles:
- src: git+https://github.com/aptiko-ansible/common.git
  name: common

- src: git+https://github.com/aptiko-ansible/apache.git
  name: apache

- src: git+https://github.com/aptiko-ansible/apache-vhost.git
  name: apache-vhost

- src: git+https://gitlab.grnet.gr/digigov-oss/ansible/nextcloud.git
  name: nextcloud

- src: git+https://gitlab.grnet.gr/digigov-oss/ansible/mysql.git
  name: mysql

- src: git+https://gitlab.grnet.gr/digigov-oss/ansible/nextcloud-collabora.git
  name: nextcloud-collabora

- src: git+https://gitlab.grnet.gr/digigov-oss/ansible/mail-satellite.git
  name: mail-satellite
