---

- name: Setup trusted domain
  become: yes
  become_user: www-data
  replace:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    regexp: '''trusted_domains''(\s|\n)*=>(\s|\n)*array(\s|\n)*\((.|\n)*?\)(\s|\n)*,\s*\n'
    replace: |
      'trusted_domains' => 
        array (
          0 => '{{ nextcloud_fqdn }}',
        ),
  notify:
    - Restart php-fpm

- name: Setup default_phone_region
  become: yes
  become_user: www-data
  lineinfile:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    regexp: default_phone_region
    line: "  'default_phone_region' => '{{ default_phone_region }}',"
    insertbefore: '^\s*\);\s*$'
  notify:
    - Restart php-fpm

- name: Setup base URL for command-line tools
  become: yes
  become_user: www-data
  lineinfile:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    regexp: overwrite.cli.url
    line: "  'overwrite.cli.url' => 'https://{{ nextcloud_fqdn }}/',"
    insertbefore: '^\s*\);\s*$'
  notify:
    - Restart php-fpm

- name: Setup pretty URLs
  become: yes
  become_user: www-data
  lineinfile:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    regexp: htaccess.RewriteBase
    line: "  'htaccess.RewriteBase' => '/',"
    insertbefore: '^\s*\);\s*$'
  notify:
    - Update htaccess
    - Restart php-fpm

- name: Setup activity_use_cached_mountpoints
  # This parameter enables users to view activities in group folders or external
  # storages. However it isn't without problems: please take a good look at
  # https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/activity_configuration.html#activities-in-groupfolders-or-external-storages
  become: yes
  become_user: www-data
  lineinfile:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    regexp: activity_use_cached_mountpoints
    line: "  'activity_use_cached_mountpoints' => true,"
    insertbefore: '^\s*\);\s*$'
  when: "'groupfolders' in nextcloud_apps"
  notify:
    - Restart php-fpm

- name: Configure memcache.local
  become: yes
  become_user: www-data
  lineinfile:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    regexp: "memcache.local"
    line: '  ''memcache.local'' => ''\\OC\\Memcache\\Redis'','
    insertbefore: '^\s*\);\s*$'
  notify:
    - Restart php-fpm

- name: Configure memcache.locking
  become: yes
  become_user: www-data
  lineinfile:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    regexp: "memcache.locking"
    line: '  ''memcache.locking'' => ''\\OC\\Memcache\\Redis'','
    insertbefore: '^\s*\);\s*$'
  notify:
    - Restart php-fpm

- name: Check whether config.php contains a redis block
  become: yes
  become_user: www-data
  lineinfile:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    regexp: "redis"
    state: absent
  check_mode: yes  # The file will never actually be modified
  register: redis
  changed_when: not redis.found

- name: Ensure config.php contains a redis block
  become: yes
  become_user: www-data
  lineinfile:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    line: "  'redis' => array ( ),"
    insertbefore: '^\s*\);\s*$'
  when: not redis.found
  notify:
    - Restart php-fpm

- name: Setup redis configuration in config.php
  become: yes
  become_user: www-data
  replace:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    regexp: '''redis''(\s|\n)*=>(\s|\n)*array(\s|\n)*\((.|\n)*?\)(\s|\n)*,\s*\n'
    replace: |
      'redis' => 
        array (
          'host' => 'localhost',
          'port' => 6379,
        ),
  notify:
    - Restart redis
    - Restart php-fpm

- name: Configure maintenance_window
  become: yes
  become_user: www-data
  lineinfile:
    path: /var/www/{{ nextcloud_fqdn }}/nextcloud/config/config.php
    regexp: "maintenance_window_start"
    line: '  ''maintenance_window_start'' => {{ nextcloud_maintenance_window_start }},'
    insertbefore: '^\s*\);\s*$'
  # This does not need to restart fpm because it's only used by cron
