---

- name: Generate private key for meet.jitsi
  community.crypto.openssl_privatekey:
    path: /etc/prosody/certs/meet.jitsi.key
    owner: prosody
    group: prosody

- name: Create certificate signing request for meet.jitsi
  community.crypto.openssl_csr:
    path: /etc/prosody/certs/meet.jitsi.csr
    privatekey_path: /etc/prosody/certs/meet.jitsi.key
    common_name: meet.jitsi
    organization_name: Jitsi

- name: Generate certificate for meet.jitsi
  community.crypto.x509_certificate:
    path: /etc/prosody/certs/meet.jitsi.crt
    csr_path: /etc/prosody/certs/meet.jitsi.csr
    privatekey_path: /etc/prosody/certs/meet.jitsi.key
    provider: selfsigned
    owner: prosody
    group: prosody

- name: Generate private key for auth.meet.jitsi
  community.crypto.openssl_privatekey:
    path: /etc/prosody/certs/auth.meet.jitsi.key
    owner: prosody
    group: prosody

- name: Create certificate signing request for auth.meet.jitsi
  community.crypto.openssl_csr:
    path: /etc/prosody/certs/auth.meet.jitsi.csr
    privatekey_path: /etc/prosody/certs/auth.meet.jitsi.key
    common_name: auth.meet.jitsi
    organization_name: Jitsi

- name: Generate certificate for auth.meet.jitsi
  community.crypto.x509_certificate:
    path: /etc/prosody/certs/auth.meet.jitsi.crt
    csr_path: /etc/prosody/certs/auth.meet.jitsi.csr
    privatekey_path: /etc/prosody/certs/auth.meet.jitsi.key
    provider: selfsigned
    owner: prosody
    group: prosody
