---
- name: Gather jvb and jibri facts
  setup:
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['jitsi_jvb'] | union(groups['jibri'])}}"

- name: Install apt packages required for Jitsi
  apt:
    name:
      - openjdk-11-jdk-headless
      - lua5.1
      - prosody
      - prosody-modules
      - git
      - maven
      - nodejs
      - make
      - unzip
    autoremove: true

- import_tasks: create_certificates.yml
- import_tasks: meet.yml
- import_tasks: prosody.yml
- import_tasks: jicofo.yml
- import_tasks: statistics.yml
  tags:
    - jitsi_statistics
  when: prometheus_server_ips|default("False")
