namespace: grnet
name: coturn
version: 0.1.0-dev0
readme: README.md
authors:
- Antonis Christofides <achristofides@admin.grnet.gr>
description: Miscellaneous roles for team collaboration
license:
- GPL-3.0-or-later
tags: []
dependencies:
  git+https://github.com/aptiko/aptiko.general.git: master
repository: https://github.com/grnet/team-collaboration-toolkit
documentation: https://team-collaboration-toolkit.readthedocs.io
homepage: https://github.com/grnet/team-collaboration-toolkit
issues: https://github.com/grnet/team-collaboration-toolkit/issues
build_ignore: []

