---
 
- name: Install apt packages required for coturn
  apt:
    name:
      - coturn
      - ssl-cert
      - certbot

- name: Check if letsencrypt certificate exists
  stat:
    path: /etc/letsencrypt/live/{{ coturn_fqdn }}
  register: letsencryptdir

- name: Ensure ferm allows certbot
  meta: flush_handlers

- name: Install letsencrypt certificate
  command: certbot certonly --standalone --non-interactive --agree-tos -m {{ letsencrypt_admin }} -d {{ coturn_fqdn }}
  when: letsencrypt and not letsencryptdir.stat.exists

- name: Allow firewall for STUN and TURN
  lineinfile:
    path: /etc/ferm/ansible-late
    line: "proto (tcp udp) dport 443 ACCEPT;"
  notify: Reload ferm
  when: coturn_use_ferm

- name: Install turnserver.conf
  template:
    src: turnserver.conf
    dest: /etc/turnserver.conf
  notify: Restart coturn

- name: Ensure systemd coturn drop-in directory exists
  file:
    path: /etc/systemd/system/coturn.service.d
    state: directory

- name: Install systemd coturn drop-in configuration file
  template:
    src: coturn-systemd.conf
    dest: /etc/systemd/system/coturn.service.d/coturn.conf
  notify: Restart coturn
