---

- name: Install apt packages required for coturn
  apt:
    name: coturn

- name: Allow firewall for STUN and TURN
  lineinfile:
    path: /etc/ferm/ansible-late
    line: "proto (tcp udp) dport 443 ACCEPT;"
  notify: Reload ferm
  when: coturn_use_ferm

- name: Install turnserver.conf
  template:
    src: turnserver.conf
    dest: /etc/turnserver.conf
  notify: Restart coturn

- name: Ensure systemd coturn drop-in directory exists
  file:
    path: /etc/systemd/system/coturn.service.d
    state: directory

- name: Install systemd coturn drop-in configuration file
  template:
    src: coturn-systemd.conf
    dest: /etc/systemd/system/coturn.service.d/coturn.conf
  notify: Restart coturn