---
dependencies:
  - role: aptiko.general.postgresql

galaxy_info:
  author: Antonis Christofides
  description: Install Synapse with PostgreSQL on Debian/Ubuntu
  license: GPLv3
  min_ansible_version: "2.19"
